### ISSUE TITLE
A suggestion for Clear StartMenu

### ISSUE THREAD

**Issue by wzvidewo** [tranht17/WinTune#10]
I have a suggestion, can you add a warning when clicking "Clear StartMenu"? The first time I used your software, I accidentally deleted the start menu that I carefully organized. I regret now that I didn't pay attention to the button. Text.

**Comment by hoochanlon** [comment]
Ditto.  

StartMenu Manager

* [ ] Clear StartMenu
* [ ] Recovery  StartMenu

It might also be interesting to replace the dragon with a different picture

**Comment by tranht17** [comment]
In the upcoming version, I will add the backup/restore startmenu layout feature

@hoochanlon `It might also be interesting to replace the dragon with a different picture`
I'm working on it, an upcoming version will allow you to turn it off or replace it with another image.

**Comment by lovelyelfpop** [comment]
同样的  开始菜单的磁贴被清空了。后悔用这个软件

**Comment by tranht17** [comment]
@lovelyelfpop I'm sorry about that.
My software still has many shortcomings and I will gradually improve it.
I hope you and everyone will report errors and support me so that this software can become more and more perfect.
