### ISSUE TITLE
Startup Manager Crash

### ISSUE THREAD

**Issue by megabugman** [tranht17/WinTune#14]
App crashed once when clicking on Startup Manager, now crashes on every start.

Log:
================= WinTune - Error =================
Time     :20240714014837
OSVersion:10.0.19045
Is64bitOS:1
Message  :Invalid index.
Stack    :*#1 (4326) : [Array.Prototype.__Item.Get] sExt := StrSplit(ext,A_Space)[1]
*#1 (4326) : [FindTarget] sExt := StrSplit(ext,A_Space)[1]
*#1 (4294) : [RegistryLoad] rTarget := FindTarget(v, &attr:="")
*#1 (4241) : [BtnStartupManager_Click] %iType%Load(LVStartupManager, A_Index, StartupType[A_Index])
*#1 (3185) : [NavItem_Click] CurrentTabCtrls := %Layout[g.NavSelected].Fn%(g, g.NavSelected)
> Gui

================= WinTune - Error =================
Time     :20240714015214
OSVersion:10.0.19045
Is64bitOS:1
Message  :Invalid index.
Stack    :*#1 (4326) : [Array.Prototype.__Item.Get] sExt := StrSplit(ext,A_Space)[1]
*#1 (4326) : [FindTarget] sExt := StrSplit(ext,A_Space)[1]
*#1 (4294) : [RegistryLoad] rTarget := FindTarget(v, &attr:="")
*#1 (4241) : [BtnStartupManager_Click] %iType%Load(LVStartupManager, A_Index, StartupType[A_Index])
*#1 (3185) : [NavItem_Click] CurrentTabCtrls := %Layout[g.NavSelected].Fn%(g, g.NavSelected)
*#1 (3157) : [CreateGui] NavItem_Click(g, IniRead("config.ini", "General", "LastTab", 1))
*#1 (4913) : [] CreateGui()
> Auto-execute

![bug](https://github.com/user-attachments/assets/054ac8e6-c44e-42c2-b7fa-34ee6598e2f1)

Startup.txt
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --no-startup-window --win-session-start
%windir%\system32\SecurityHealthSystray.exe

**Comment by tranht17** [comment]
Can you run [this](https://raw.githubusercontent.com/tranht17/WinTune/main/Debug/Debug_Startup.exe) and show me the contents of the "Startup_Error.txt" file that is generated?

**Comment by megabugman** [comment]
Startup_Error.txt

C:\Windows\system32\cmd.exe /q /c rmdir /s /q "C:\Users\%username%\AppData\Local\Microsoft\OneDrive\24.126.0623.0001\i386"
