### ISSUE TITLE
UWP Apps Message  :(0x80070490) Element not found.

### ISSUE THREAD

**Issue by megabugman** [tranht17/WinTune#15]
happens with UWP Apps in Not Installed Mode

================= WinTune v2.5.0 =================
Time     :20240720130426
OSVersion:10.0.22621
Is64bitOS:1
Message  :(0x80070490) Element not found.
Stack    :*#1 (629) : [ComCall] ComCall(9, this.IPackage2, 'Ptr*', IUriRuntimeClass:=ComValue(13, 0))
*#1 (629) : [PackageManager.IPackage.Prototype.UriLogo.get] ComCall(9, this.IPackage2, 'Ptr*', IUriRuntimeClass:=ComValue(13, 0))
*#1 (637) : [PackageManager.IPackage.Prototype.RawUri.get] Return (ComCall(16, this.UriLogo, "Ptr*", &value:=0), PackageManager.HStringToStr(value))
*#1 (642) : [PackageManager.IPackage.Prototype.Logo.get] Logo := this.RawUri
*#1 (4623) : [LoadLV] IconIndex := IL_Add(ImageListID, rList[i].Logo, 1)
*#1 (4643) : [SwichInstalled] LoadLV()
> Gui

================= WinTune v2.5.0 =================
Time     :20240720130813
OSVersion:10.0.22621
Is64bitOS:1
Message  :(0x80070490) Element not found.
Stack    :*#1 (629) : [ComCall] ComCall(9, this.IPackage2, 'Ptr*', IUriRuntimeClass:=ComValue(13, 0))
*#1 (629) : [PackageManager.IPackage.Prototype.UriLogo.get] ComCall(9, this.IPackage2, 'Ptr*', IUriRuntimeClass:=ComValue(13, 0))
*#1 (637) : [PackageManager.IPackage.Prototype.RawUri.get] Return (ComCall(16, this.UriLogo, "Ptr*", &value:=0), PackageManager.HStringToStr(value))
*#1 (642) : [PackageManager.IPackage.Prototype.Logo.get] Logo := this.RawUri
*#1 (4623) : [LoadLV] IconIndex := IL_Add(ImageListID, rList[i].Logo, 1)
*#1 (4598) : [BtnPackageManager_Click] LoadLV()
*#1 (3206) : [NavItem_Click] CurrentTabCtrls := %Layout[g.NavSelected].Fn%(g, g.NavSelected)
> Gui

================= WinTune v2.5.0 =================
Time     :20240720131445
OSVersion:10.0.22621
Is64bitOS:1
Message  :(0x80070490) Element not found.
Stack    :*#1 (629) : [ComCall] ComCall(9, this.IPackage2, 'Ptr*', IUriRuntimeClass:=ComValue(13, 0))
*#1 (629) : [PackageManager.IPackage.Prototype.UriLogo.get] ComCall(9, this.IPackage2, 'Ptr*', IUriRuntimeClass:=ComValue(13, 0))
*#1 (637) : [PackageManager.IPackage.Prototype.RawUri.get] Return (ComCall(16, this.UriLogo, "Ptr*", &value:=0), PackageManager.HStringToStr(value))
*#1 (642) : [PackageManager.IPackage.Prototype.Logo.get] Logo := this.RawUri
*#1 (4623) : [LoadLV] IconIndex := IL_Add(ImageListID, rList[i].Logo, 1)
*#1 (4643) : [SwichInstalled] LoadLV()
> Gui

Also consider fixing the blinking cursor, the text field should disabled when none/default image is selected
![bug](https://github.com/user-attachments/assets/73b73032-c218-46ba-80d1-34e106687984)

**Comment by tranht17** [comment]
It's strange when encountering this, it seems to come across an app without a logo.
Can you try running [this fixed version](https://www.mediafire.com/file/p08j4jaumxj1dqt/WinTune_Fixed.exe/file) to see if there are any errors?
If it works, can you share information (FamilyName or FullName) about the app without that logo?

**Comment by megabugman** [comment]
Issue persists with fixed version:

https://github.com/user-attachments/assets/de5fb802-4358-4e23-9495-431ea041f76c

**Comment by tranht17** [comment]
You can try again with [this version](https://www.mediafire.com/file/zlun26mxk0bfj53/WinTune_Fixed2.exe/file) and send me the log.txt file.
Thanks very much.

**Comment by megabugman** [comment]
[log.txt](https://github.com/user-attachments/files/16351927/log.txt)
There you go.
