### ISSUE TITLE
Parameters support

### ISSUE THREAD

**Issue by truefriend-cz** [tranht17/WinTune#5]
Hello mega super Developer. would it be possible to add to the application support for launching the application via the command line along with loading a previously saved configuration file (profile)?

For example:

`WinTune.exe WinTune_OptimizeConfig.json`

And then, in order to start the application, the OS settings were automatically performed according to the profile file and the application was closed again (in case of a request to disable Windows Defender, the computer was also automatically restarted).

**Comment by tranht17** [comment]
Thank you for your interest in this application.
I also thought about this before but then canceled it because I was afraid that bad guys would take advantage of that feature to sabotage the user's system.
It is dangerous to let an application run automatically via the command line in silence.

**Comment by truefriend-cz** [comment]
Well from what I can see, the bad guys managed to scare the developer into being afraid to put a feature in there. I think that if such a situation would arise, this feature would help a lot more people than it would be abused. If you are really serious about this reason then you can maybe disable Defender from the automatic settings. Otherwise, I can't imagine why a potential attacker would want to disable services and functionality. Competing products allow it to be run via the command line and I haven't noticed a problem with it. For example, utilities from Sordum.org (Defender disabler), or "Optimizer", etc. I think these concerns are unnecessary.

**Comment by tranht17** [comment]
Command line support has been added since version 1.6.0.
Thanks!
