### ISSUE TITLE
Startup Manager Crash

### ISSUE THREAD

**Issue by megabugman** [tranht17/WinTune#7]
App crahes on W10 when clicking on Startup Manager.
Log: 

================= Error =================
Time:    20240409023351
Message: Function recursion limit exceeded.
Stack:   *#1 (3861) : [SplitPath] SplitPath(InPath,, &dir, &ext, &name_no_ext)
*#1 (3861) : [FindTarget] SplitPath(InPath,, &dir, &ext, &name_no_ext)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
*#1 (3864) : [FindTarget] r := FindTarget(ExpandEnvironmentStrings(InPath), &rFileAttr)
... 612 more

**Comment by tranht17** [comment]
It seems the problem lies in the command line.
You can download the file [Debug_Startup.exe](https://www.mediafire.com/file/ca5sfxfuwri4tbg/Debug_Startup.exe/file) and run it, send me the generated "Startup.txt" file or its contents.
Thank you

**Comment by megabugman** [comment]
merge this to crash:

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]
"Test"="D:\\Test.exe --autostart --minimized"
